-- ============================================
-- Deshabilitar RLS Temporalmente para Desarrollo
-- ============================================
-- ⚠️ SOLO PARA DESARROLLO/TESTING
-- NO EJECUTAR EN PRODUCCIÓN
-- ============================================

-- Deshabilitar RLS en todas las tablas principales
ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE timelogs DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_sheets DISABLE ROW LEVEL SECURITY;
ALTER TABLE payrolls DISABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_payment_employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_deductions DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_payrolls DISABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_debts DISABLE ROW LEVEL SECURITY;
ALTER TABLE banks DISABLE ROW LEVEL SECURITY;
ALTER TABLE creditors DISABLE ROW LEVEL SECURITY;
ALTER TABLE timeoff_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE timeoffs DISABLE ROW LEVEL SECURITY;
ALTER TABLE terminations DISABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_languages DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_disabilities DISABLE ROW LEVEL SECURITY;
ALTER TABLE document_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE complaints DISABLE ROW LEVEL SECURITY;
ALTER TABLE complaint_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;

-- ============================================
-- Para volver a habilitar RLS más tarde:
-- ============================================
-- ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
-- (repetir para cada tabla)

