import { Injectable } from '@angular/core';

interface PhraseContext {
  dayOfWeek: number;
  dayOfMonth: number;
  hour: number;
  isLate: boolean;
  type: string;
  exitDiffMinutes?: number;
  isExitPunctual?: boolean;
}

type PhraseGen = (name: string, gender?: 'M' | 'F') => string;

@Injectable({ providedIn: 'root' })
export class TimeclockPhrasesService {
  /** ===================== CUMPLEAÑOS ===================== */
  private readonly BIRTHDAY: string[] = [
    '¡Feliz cumpleaños! Que este nuevo año de vida esté lleno de éxitos',
    '¡Hoy es tu día especial! El equipo te desea lo mejor',
    '¡Cumpleaños feliz! Gracias por ser parte de este equipo increíble',
    '¡Feliz cumple! Que la vida te siga regalando momentos geniales',
    '¡Hoy celebramos tu vida! Felicidades en tu día',
    '¡El cumpleañero del día! Que sea un año lleno de logros',
    '¡Feliz cumpleaños, crack! El equipo te aprecia mucho',
    '¡Hoy soplas las velas! Que todos tus deseos se hagan realidad',
    '¡Cumpleaños y puntual! Eso habla de un verdadero campeón',
    '¡Muchas felicidades! Hoy el universo celebra que existes',
    '¡Feliz vuelta al sol! Que este nuevo ciclo sea el mejor',
    '¡El protagonista del día llegó! Feliz cumpleaños',
    '¡Hoy es un gran día para celebrarte! Felicidades',
    '¡Que viva el cumpleañero! Este año va a ser increíble',
    '¡Feliz día! Un año más de experiencia, sabiduría y éxito',
    '¡Brindamos por ti hoy! Feliz cumpleaños, compañero',
    '¡Se merece un aplauso! Feliz cumpleaños',
    '¡Hoy no solo marcas entrada, marcas otro año de grandeza!',
    '¡Feliz cumple! Ojalá el día de hoy sea tan especial como tú',
    '¡Llegó el cumpleañero! Todos en el equipo te mandamos un abrazo',
    '¡Un año más y cada vez mejor! Felicidades',
    '¡Hoy brillas más que nunca! Feliz cumpleaños',
    '¡Celebramos tu existencia! Gracias por iluminar el equipo',
    '¡Feliz cumpleaños! Que cada día sea una nueva aventura',
    '¡Hoy el mundo es tuyo! Disfruta tu día al máximo',
    '¡Feliz cumple! Que la torta esté tan dulce como tu día',
    '¡Hoy es tu día, campeón! El equipo te celebra',
    '¡Felicidades! Que este año supere todos los anteriores',
    '¡Un brindis virtual por ti! Feliz cumpleaños',
    '¡Hoy marcas entrada y marcas un año más de vida! Felicidades',
    '¡Es tu cumpleaños y estás aquí! Eso es dedicación nivel premium',
    '¡Feliz cumple, máquina! Ojalá te lluevan bendiciones',
    '¡El equipo Black Dog te desea el mejor cumpleaños del mundo!',
    '¡Hoy naciste y el mundo se puso mejor! Feliz día',
    '¡Felicidades! Hoy tu marcación viene con confeti incluido',
    '¡Cumpleaños feliz! Que los perritos te manden buenas vibras',
    '¡Hoy se celebra al crack del equipo! Feliz cumple',
    '¡Feliz vuelta al sol! Que este año sea de pura abundancia',
    '¡Hoy estás de cumple y el equipo está de fiesta!',
    '¡Otro año más siendo parte de esta familia! Felicidades',
    '¡Feliz cumpleaños! Si fueras un perrito, hoy tendrías doble snack',
    '¡Que tu día sea tan genial como tú! Feliz cumple',
    '¡Hoy es el día del MVP del equipo! Felicidades',
    '¡Feliz cumple! Tu energía merece celebrarse cada día',
    '¡El equipo entero te abraza hoy! Feliz cumpleaños',
    '¡Hoy sopla las velas y pide un deseo grande!',
    '¡Feliz día! Eres una pieza irremplazable de este equipo',
    '¡Cumpleaños y marcando a tiempo! Eso es compromiso de ley',
    '¡Hoy se celebra a alguien especial! Felicidades, crack',
    '¡Feliz cumpleaños! Que el café de hoy sepa a victoria',
    '¡Otro año sumando éxitos! Feliz cumple, compañero',
    '¡Hoy tu entrada viene con pastel virtual incluido!',
    '¡Feliz cumple! Que tu año nuevo personal sea épico',
  ];

  /** ===================== INICIO DE ALMUERZO ===================== */
  private readonly LUNCH_START: string[] = [
    '¡Buen provecho! Te lo mereces',
    'A recargar energías, que la tarde espera',
    'Hora de almorzar, ¡disfrútalo!',
    'Almuerzo merecido, buen provecho',
    'Recarga las pilas, la segunda mitad te necesita fuerte',
    'Buen apetito, ¡regresa con todo!',
    'Hora del combustible, ¡a comer bien!',
    'Te ganaste ese almuerzo, provecho',
    'A llenar el tanque para la tarde',
    'Almuerzo time, que sea delicioso',
    'Provecho, crack. Regresa listo para la segunda ronda',
    'Hora de la recarga. ¡Come rico!',
    'Bien merecido ese break. ¡Buen provecho!',
    'A disfrutar el almuerzo como se merece',
    'Pausa para recargar. ¡Que esté bueno!',
    '¡A comer! Que el estómago también tiene horario',
    'Hora de la mejor reunión del día: tú y tu comida',
    'Break oficial de productividad. ¡Buen provecho!',
    'El almuerzo es sagrado, disfrútalo',
    'Media jornada completada, premio: ¡almuerzo!',
    'Tiempo de sancocho... o lo que sea que traigas',
    'Tu estómago aplaudió esa marcación',
    'La barriga manda, y dijo que es hora',
    'Que el arroz esté suelto y la carne jugosa',
    'A comer como panameño: con ganas',
    'Tu cuerpo pidió timeout y se lo merece',
    'La productividad también se alimenta, buen provecho',
    'Dale play al almuerzo, pausa el trabajo',
    'El plato del día te espera con los brazos abiertos',
    'Hora del intermedio más delicioso del día',
    'Ve a comer tranquilo, el trabajo te espera recargado',
    'Pausa nutricional autorizada. ¡Provecho!',
    'El estómago marcó su propia salida a almuerzo',
    'Hora de darle amor a la barriga',
    'El almuerzo es el premio de la mañana productiva',
    'A por ese plato bien ganado',
    'La cocina te llama y no se le dice que no',
    'Medio día de campeón completado. Premio: comida',
    'Tu almuerzo lleva esperándote toda la mañana',
    'A recargar la batería humana. ¡Provecho!',
    'La mesa está servida para el trabajador estrella',
    'Desconecta un rato y conecta con tu plato',
    'Hora de la cita más importante del día: tú y tu almuerzo',
    'Break merecido. Que cada bocado sepa a victoria',
    'El menú del día: descanso + comida + recarga',
    'Respira, come, recarga. En ese orden',
    'Almuerzo mode: activado. Disfrútalo',
    'Hora de alimentar al campeón',
    'El almuerzo no se negocia, ¡buen provecho!',
    'Tu estómago dice gracias por la marcación puntual',
    'A disfrutar la pausa más sabrosa del día',
    'La comida te espera como perrito fiel',
    'Pausa gastronómica merecida. ¡Come rico!',
    'Hora de la recarga energética oficial',
    'El almuerzo es la gasolina del trabajador estrella',
    'A darle lo que el cuerpo pide: comidita rica',
    'Tu plato ya está impaciente, ve a rescatarlo',
    'El descanso alimenticio más merecido del día',
    'Hora de nutrir el cuerpo y el alma',
    'Almuerzo bien ganado, que sea bien disfrutado',
    'La barriga no espera, y tiene razón. ¡Provecho!',
    'Come con calma, regresa con fuerza',
    'El mejor break del día acaba de empezar',
  ];

  /** ===================== FIN DE ALMUERZO ===================== */
  private readonly LUNCH_END: string[] = [
    '¡De vuelta! Ahora con más energía',
    'Recargado y listo para la segunda mitad',
    'Regresaste, ¡a cerrar el día con fuerza!',
    'Con las pilas full para la tarde',
    'De vuelta al ruedo, ¡dale con todo!',
    'Almuerzo completado, modo trabajo reactivado',
    'Ya comiste, ahora a producir',
    'Regreso puntual del almuerzo, eso se nota',
    'La tarde es tuya, ¡a conquistarla!',
    'Energía recargada al 100%, vamos',
    'De vuelta y con más ganas que antes',
    'Panza llena, corazón contento, ¡a trabajar!',
    'Reingreso exitoso. Modo productividad: ON',
    'La segunda mitad del día empieza ahora',
    'Volviste con todo, se nota la recarga',
    'Post-almuerzo y sin sueño, campeón',
    'El almuerzo le dio superpoderes, ¿verdad?',
    'Regresó antes que el sueño post-almuerzo',
    'A las 3pm veremos si la siesta puede contigo',
    'Listo para el round 2 de la jornada',
    'Barriga llena, productividad también',
    'Ya con la pila recargada, dale',
    'De vuelta al ring para el segundo round',
    'Que no te gane el sueño post-almuerzo',
    'Regresaste como nuevo, a darle',
    'La recarga fue exitosa. Ahora a rendir',
    'Volviste con la fuerza del sancocho',
    'Panza satisfecha, mente lista para trabajar',
    'El combustible fue cargado, ahora a rodar',
    'De vuelta y con la actitud al máximo',
    'Regreso perfecto. La tarde es toda tuya',
    'Se nota que comiste bien, viene recargado',
    'Almuerzo check. Productividad check. ¡Vamos!',
    'La segunda mitad será mejor que la primera',
    'Ya comiste, ya descansaste, ahora a brillar',
    'Post-almuerzo y con más energía que en la mañana',
    'Regresaste puntual, eso habla de disciplina',
    'El almuerzo te sentó de maravilla, se nota',
    'Back to business. La tarde espera grandes cosas',
    'Hora de demostrar que la tarde también se gana',
    'La recarga nutricional fue un éxito total',
    'Volviste listo para conquistar lo que queda del día',
    'De vuelta con las pilas al 200%',
    'El sueño post-almuerzo no tiene chance contigo',
    'Regreso triunfal del almuerzo. ¡A darle!',
    'Alimentado y motivado, combo ganador',
    'La tarde arranca con todo gracias a tu regreso',
    'De vuelta al campo de batalla, bien alimentado',
    'Almuerzo superado, ahora a superar expectativas',
    'Ni la siesta pudo detenerte, crack',
    'La productividad de la tarde empieza contigo',
    'Regresaste más fuerte que cuando te fuiste',
    'El almuerzo fue bueno, la tarde será mejor',
    'De vuelta y ready. La tarde es nuestra',
    'Fuel loaded. Engine on. A darle',
    'Tu regreso le pone energía a toda la oficina',
    'La comida te recargó las ganas, se nota',
    'Post-lunch mode: máxima productividad',
    'Volviste con sabor a victoria',
    'El almuerzo fue tu pit stop, ahora a acelerar',
    'De vuelta justo a tiempo. La tarde te necesita',
    'Alimentado, descansado y listo para la acción',
    'Regreso al ruedo con fuerza renovada',
  ];

  /** ===================== ALMUERZO EXCEDIDO (LUNCH_OVERTIME) ===================== */
  private readonly LUNCH_OVERTIME: string[] = [
    '¿Te comiste el restaurante entero?',
    'El almuerzo no era buffet libre, compañero',
    '¿Fuiste a almorzar o a cocinar el sancocho desde cero?',
    'El almuerzo era de una hora, no de una era geológica',
    '¿Te perdiste en el menú o en el camino de regreso?',
    'El postre no estaba incluido en la hora de almuerzo',
    '¿Almorzaste o fuiste a pescar tu propio pescado?',
    'El delivery llegó más rápido que tú del almuerzo',
    'Tu almuerzo duró más que una película de Marvel',
    '¿Te fuiste a almorzar o a cultivar el arroz?',
    'Parece que el almuerzo se convirtió en cena',
    'El chef te estará extrañando, pero nosotros más',
    '¿Le pediste al mesero que te leyera todo el menú?',
    'Almuerzo extendido detectado. ¿Había postre gratis?',
    'El reloj dice que fue un almuerzo gourmet',
    '¿El restaurante te puso a lavar platos?',
    'Eso fue un almuerzo o un tour gastronómico',
    'Alerta: almuerzo tipo domingo familiar detectado',
    'Pensamos que te habías mudado al restaurante',
    '¿El mesero te trajo la cuenta muy lento o qué?',
    'Ese almuerzo duró más que la fila del banco',
    'Tu almuerzo tuvo más actos que una novela',
    'Houston, tenemos un almuerzo extendido',
    'El arroz se cocinó y enfrió mientras almorzabas',
    '¿Te cobraron por hora en el restaurante?',
    'Volviste, pero el almuerzo ya pidió pensión',
    'Tu almuerzo necesitó intermedio y segundo acto',
    'El sancocho se hizo y se repitió mientras almorzabas',
    '¿Fuiste a comer o a una degustación de 12 tiempos?',
    'Tu almuerzo fue trending topic por largo',
    'Pensé que estabas haciendo la sobremesa del domingo',
    'Tu break de almuerzo necesitó su propio break',
    'La dieta del almuerzo de hora incluía postre extendido',
    'Tu almuerzo fue más largo que la Cinta Costera',
    'Se nota que disfrutaste... quizás demasiado',
    '¿Había sopa, arroz, carne, ensalada Y repetición?',
    'El almuerzo de hoy se fue a overtime',
    'Tu estómago agradece, pero el reloj no tanto',
    'Ese almuerzo merecía su propia reservación',
    'Almuerzo épico, pero la puntualidad se quedó en la mesa',
    '¿El Uber se perdió o el restaurante estaba en Colón?',
    'Tu almuerzo tuvo más capítulos que Game of Thrones',
    '¿Estabas almorzando o esperando que madurara el plátano?',
    'Eso fue almuerzo o seminario de gastronomía',
    'El almuerzo ya tiene su propia zona horaria',
    'Te fuiste a la una y volviste en otra era',
    'Tu almuerzo podría tener su propio documental',
    'Ni el corredor del Canal tarda tanto en su almuerzo',
    'El postre era opcional, no obligatorio con repetición',
    'Ese almuerzo necesitaba permiso de la ONU',
    '¿Fuiste a almorzar o a una boda?',
    'La fonda ya te tiene silla VIP reservada',
    'Tu almuerzo duró más que la cola del Metro',
    'Lo de hoy fue almuerzo con prórroga y penales',
    '¿Te tocó esperar al que hace las tortillas a mano?',
    'El almuerzo se pasó de largo como bus del corredor',
    'Si el almuerzo fuera maratón, sacabas medalla',
    'Nota mental: tu almuerzo necesita supervisor',
    'El mundo cambió mientras almorzabas',
    'Tu almuerzo duró lo que un partido de cricket',
    '¿Estabas almorzando o haciendo la digestión también?',
    'El reloj ya estaba preocupado por ti',
    'Tu almuerzo fue un proyecto de largo plazo',
    'Ni el arroz con coco tarda tanto en hacerse',
    'Ese no fue almuerzo, fue festival gastronómico',
    'La sobremesa no estaba en el contrato, compañero',
    'El almuerzo tomó vida propia y pidió extensión',
    'Volviste cuando el café de la tarde ya estaba frío',
    'Almuerzo extendido: la secuela que nadie pidió',
    'Tu almuerzo fue tan largo que cambió la marea',
    'El mesero ya te adoptó como familia',
    '¿Almorzaste o redactaste tu autobiografía en el restaurante?',
    '¿Te quedaste dormido en la sobremesa?',
    'Ese almuerzo necesitó su propio permiso especial',
    'El almuerzo duró más que el tranque de la Tumba Muerto',
    'La tarde casi se hace de noche esperándote',
    'Tu almuerzo fue más extenso que el Canal',
    '¿Fuiste a almorzar al interior y volviste?',
    'El tiempo vuela, pero tu almuerzo voló más',
    'Tu almuerzo fue tan largo que salimos en las noticias',
    '¿Te sirvieron en orden alfabético o qué pasó?',
    'El almuerzo extendido es un arte, y tú eres Picasso',
    'Pensamos en mandar un equipo de rescate al restaurante',
    'Tu almuerzo tuvo créditos finales y escena post-créditos',
    'El restaurante te puso en el cuadro de honor por fidelidad',
    'Tu almuerzo necesitó visa de extensión de permanencia',
    'Las plantas del restaurante crecieron mientras almorzabas',
    'El mesero ya te considera parte de su familia extendida',
    'Tu almuerzo tuvo más temporadas que Breaking Bad',
    'Pensamos que te habías ido a cultivar tu propia comida',
    '¿Te cobraron parking en el restaurante por la estadía?',
    'Tu almuerzo duró tanto que Netflix te recomendó una serie',
    'El delivery hubiera ido y vuelto 3 veces en ese tiempo',
    'Hasta Google Maps perdió tu ubicación durante el almuerzo',
    'Tu almuerzo se clasificó como "experiencia turística"',
    'El menú del día ya cambió al menú de la noche',
    'Tu almuerzo fue trending en la oficina',
    'Ni en cena de Navidad tardan tanto, compañero',
  ];

  /** ===================== SALIDA ===================== */
  private readonly EXIT: string[] = [
    'Jornada completada, ¡buen trabajo hoy!',
    'Misión cumplida. Descansa, te lo mereces',
    'Otro día exitoso, ¡hasta mañana!',
    'Buen día de trabajo. ¡Disfruta tu tarde!',
    'Cerraste el día como campeón',
    'Hora de descansar. ¡Lo diste todo!',
    'Día completado, objetivo cumplido',
    'Te lo ganaste, buen descanso',
    'Hasta mañana, crack. Gran día hoy',
    'Día cerrado con éxito. ¡A descansar!',
    'Excelente jornada. Ve y disfruta tu tiempo',
    'Lo que se tenía que hacer, se hizo. ¡Bye!',
    'Hoy se cumplió. ¡Descansa bien!',
    'La jornada está servida. ¡Hasta mañana!',
    'Cierre perfecto. ¡Que descanses!',
    'Buen trabajo hoy, ve a disfrutar lo que queda del día',
    'Otra victoria diaria. ¡Descansa, guerrero!',
    'El día fue tuyo. Ahora es tiempo de ti',
    'Marcaste salida pero dejaste huella',
    'Hasta mañana, no sin antes decir: ¡buen trabajo!',
    'Se acabó la jornada pero no las ganas para mañana',
    'Hora de apagar el modo trabajo',
    'Ctrl+S al progreso de hoy. ¡Nos vemos!',
    'GG, bien jugado. Hasta mañana',
    'El reloj dice bye, tú dices misión cumplida',
    'Tu jornada de hoy fue un éxito total',
    'Hoy diste el máximo. Ahora recarga para mañana',
    'Salida merecida después de un día productivo',
    'Cierre de jornada exitoso. ¡Disfruta tu noche!',
    'Otro día de aportar valor al equipo. ¡Descansa!',
    'La meta del día se logró. Bien hecho',
    'Hoy dejaste tu marca, ahora ve a descansar',
    'Jornada cerrada con broche de oro',
    'Tu esfuerzo de hoy construye el éxito de mañana',
    'Game over por hoy. ¡Ganaste!',
    'Hora de descansar esa mente trabajadora',
    'El equipo agradece tu entrega de hoy',
    'Día productivo en los libros. ¡Hasta mañana!',
    'Ve a disfrutar, te lo ganaste con creces',
    'La jornada fue intensa pero la superaste',
    'Otro día más en tu historial de éxitos',
    'Hoy sumaste otro día de excelencia',
    'Cerrar el día bien es un arte, y tú lo dominas',
    'Tu trabajo de hoy hizo la diferencia',
    'Hora de la recompensa: descanso merecido',
    'Hasta mañana, campeón. Hoy fue un gran día',
    'Que el descanso sea tan bueno como tu jornada',
    'Misión del día: completada exitosamente',
    'Ve tranquilo, hoy se logró mucho',
    'El día terminó pero tu impacto se queda',
    'Salida con la frente en alto, como debe ser',
    'Hoy fuiste clave para el equipo. ¡Descansa!',
    'Otro día de demostrar tu valor. Bien hecho',
    'La jornada está servida y fue deliciosa',
    'Descansa bien, mañana hay más victorias que ganar',
    'Tu compromiso hoy fue nivel premium',
    'End of day. Beginning of rest. ¡Hasta mañana!',
    'Hoy dejaste el alma y se nota. ¡Descansa!',
    'La productividad de hoy fue legendaria',
    'Ve con la satisfacción del deber cumplido',
    'Hasta mañana, estrella. Hoy brillaste',
    'El día te pertenece y lo conquistaste. ¡Bye!',
    'Jornada épica completada. Level up',
  ];

  /** ===================== SALIDA PUNTUAL (bromas) ===================== */
  private readonly EXIT_PUNCTUAL: string[] = [
    '¡Ni un segundo más! Eso es precisión nivel reloj suizo',
    'Marcaste salida EXACTO. ¿Tenías el dedo listo?',
    'Puntualidad de salida: 10/10. Tienes un don',
    'Ni temprano ni tarde... justo a tiempo. Sospechoso...',
    'El reloj de salida y tú son mejores amigos',
    'Sale a las 4 y marca a las 4. Coincidencia? No lo creo',
    '¡Velocidad de rayo marcando salida! Nuevo récord',
    'Parece que alguien tenía planes para hoy',
    'La hora es la hora. ¡Y tú lo sabes!',
    'Más puntual que alarma de celular',
    'Ni un segundo más, ni un segundo menos. ¡Clavado!',
    'Usain Bolt marcando salida, ladies and gentlemen',
    'Exactitud de salida nivel GPS',
    '¿Estabas contando los segundos? Porque fue clavado',
    'Más puntual para salir que para entrar... interesante',
    'Speed run de marcación de salida completado',
    'Tu dedo ya estaba en el botón, ¿verdad?',
    'Puntualidad es puntualidad, tanto de entrada como de salida',
    'Le pusiste alarma para marcar salida, admítelo',
    'La salida más precisa del mes. ¡Felicidades!',
    'En punto. Milimétrico. Cirujano de la marcación',
    'Si la puntualidad de salida fuera deporte, serías olímpico',
    'Cuando la hora es la hora, es la hora. Punto',
    'El mundo necesita esa precisión de salida',
    'Reloj suizo: 99.9% precisión. Tú: 100%',
    'La velocidad con que marcaste salida debería ser ilegal',
    'HEADSHOT de marcación. Justo en la hora',
    'Tu reloj interno está calibrado a la perfección',
    'Sospechosamente puntual... pero se respeta',
    'Escape artist profesional. Salida perfecta',
    '¿Tenías countdown en el escritorio? Pregunto por un amigo',
    'La NASA te envidiaría esa precisión de lanzamiento',
    'Tu dedo estaba en órbita sobre el botón de salida',
    'Más puntual que el amanecer. Y eso ya es decir mucho',
    'Salida quirúrgica. Ni un milisegundo de más',
    'Esa precisión de salida debería estar en tu currículum',
    '¿Te cronometraste o fue instinto puro?',
    'El botón de salida y tú tienen una conexión especial',
    'Puntualidad de salida: podrías dar clases',
    'Eso fue una salida o un acto de magia',
    'Tu cuerpo tiene reloj atómico integrado',
    'La salida más limpia del mes. Nota: 10',
    'Ni los trenes japoneses tienen esa puntualidad de salida',
    'Estabas calentando el dedo desde las 3:55, ¿verdad?',
    '¿Cuentas los minutos o los segundos para salir?',
    'Salida perfecta. Si esto fuera gimnasia, sacabas 10.0',
    'Tu precisión de salida genera respeto y un poco de envidia',
    'El cronómetro se quitó el sombrero contigo',
    'Marcación de salida: velocidad supersónica detectada',
    'Parece que tu reloj y el del sistema están sincronizados',
    'Esa salida fue más precisa que un láser',
    '¿Practicas la marcación de salida frente al espejo?',
    'Speedrun de salida: nuevo world record',
    'Tu eficiencia de salida debería ser caso de estudio',
    'Ni el Big Ben es tan puntual como tu salida',
    'Alguien tenía el mouse flotando sobre el botón',
    'La puntualidad de tu salida tiene su propia leyenda',
    'Clavaste la salida como clavija en enchufe',
    '¿Hay un timer secreto en tu escritorio? Confiesa',
    'Marcaste tan rápido que el sistema dudó si eras humano',
    'Si tu entrada fuera tan precisa como tu salida, serías leyenda',
    'Productivo todo el día y con salida cronometrada',
    'Cero overtime. Cero retraso. Pura eficiencia',
    'Tu salida fue más rápida que decir ya me voy',
    'Hasta el reloj dijo: wow, qué precisión',
    'Tu marcación de salida merece standing ovation',
    'Flash te tiene envidia para marcar salida',
    'Ese timing de salida es un talento natural',
    'Reloj: marca la hora. Tú: ya estabas ahí',
    'Tu salida tiene la precisión de un cirujano',
    'La sincronización entre tu salida y el reloj es arte',
    'Ese clic de salida se escuchó en todo el edificio',
    'Tu salida fue más exacta que una fórmula matemática',
    'El reloj apenas pestañeó y tú ya habías marcado',
    'Precisión alemana en salida panameña. Respeto',
    'Ni los relojes atómicos del CERN son tan exactos',
    'Tu salida fue tan puntual que rompió la matrix',
    'Speedrun categoría Any% de marcación de salida',
    'Marcaste salida antes de que el reloj terminara de cambiar',
    'Tu reflejo para marcar salida debería estar en los Guinness',
    'Esa salida fue como gol de último minuto: perfecta',
    'Piloto de F1 en los pits: eso fue tu marcación de salida',
  ];

  /** ===================== SALIDA TEMPRANA (se fue antes) ===================== */
  private readonly EXIT_EARLY: string[] = [
    'Salida anticipada registrada. ¡Que estés bien!',
    'Te vas temprano, ¡ojalá todo esté bien!',
    'Salida antes de hora. Descansa y nos vemos mañana',
    'Registrado. ¡Cuídate mucho!',
    'Salida temprana anotada. Hasta pronto',
    'Nos vemos pronto. ¡Que todo esté bien!',
    'Salida anticipada. El equipo te espera mañana',
    'Registramos tu salida temprana. ¡Cuídate!',
    'Te vas antes, pero tu trabajo de hoy ya valió mucho',
    'Salida temprana. Esperamos verte mañana con toda la energía',
    'Tu salida anticipada queda registrada. ¡Ánimo!',
    'Nos vemos mañana. Lo que hiciste hoy cuenta',
    'Salida antes de lo usual. Todo bien, nos vemos pronto',
    'Tu compromiso no se mide solo en horas. ¡Cuídate!',
    'Registrado. A veces hay que salir temprano, está bien',
    'Salida anticipada. Mañana es un nuevo día',
    'El equipo entiende. ¡Que te vaya bien!',
    'Salida temprana registrada. Descansa y recarga',
    'Hoy saliste antes, mañana regresas con más fuerza',
    'Todo bien, las horas se recuperan. ¡Cuídate mucho!',
    'Tu dedicación habitual compensa cualquier salida temprana',
    'Registrado sin problema. ¡Nos vemos!',
  ];

  /** ===================== VIERNES ===================== */
  private readonly FRIDAY: string[] = [
    'Es viernes y el cuerpo lo sabe',
    'Viernes al fin, a darlo todo',
    'Último empujón de la semana',
    'Viernes: modo guerrero activado',
    'Ya huele a fin de semana',
    'Viernes con energía panameña',
    'Hoy se cierra la semana con broche de oro',
    'Viernes y el ánimo por las nubes',
    'Un viernes más conquistado',
    'La semana se gana los viernes',
    'Viernes: el día favorito de todos',
    'Hoy cerramos la semana como campeones',
    'Viernes y aquí, dando el ejemplo',
    'El viernes premia a los que no se rinden',
    'Arrancamos el viernes con toda la actitud',
    'Viernes de cerrar pendientes y celebrar logros',
    'Un viernes más demostrando de qué estamos hechos',
    'Viernes: día de rematar con estilo',
    'Hoy el viernes es tuyo, aprovéchalo',
    'Viernes legendario en construcción',
    'La mejor forma de empezar el finde: cumpliendo primero',
    'Viernes: el premio por sobrevivir la semana',
    'Casi finde y tú aquí, eso vale oro',
    'Hoy viernes se trabaja con sabrosura',
    'Viernes + actitud = combo imparable',
    'El viernes es el broche de oro de la semana',
    'Viernes con olor a libertad y cerveza fría',
    'Hoy viernes damos el último sprint de la semana',
    'La semana se cierra en viernes y se cierra bien',
    'Viernes: un paso más cerca de la playa',
    'Los viernes son para cerrar con estilo',
    'Viernes y con la misma energía del lunes. ¡Crack!',
    'El fin de semana te espera, pero primero: viernes productivo',
    'Hoy viernes el trabajo tiene sabor a recompensa',
    'Viernes: el día que hace que la semana valga la pena',
    'Un viernes bien trabajado es un finde bien disfrutado',
    'Viernes de campeones: productivos hasta el final',
    'El finde está a la vuelta de la esquina. Dale viernes',
    'Viernes mode: trabajar duro, luego descansar más duro',
    'La línea de meta semanal se llama viernes',
    'Hoy viernes se trabaja como si fuera lunes de buenas',
    'Viernes: el día más bello del calendario laboral',
  ];

  /** ===================== LUNES ===================== */
  private readonly MONDAY: string[] = [
    'Nuevo lunes, nuevas oportunidades',
    'Arrancamos la semana con todo',
    'Lunes de actitud ganadora',
    'Empieza la semana como campeón',
    'Lunes: el primer paso hacia el éxito',
    'A romperla esta semana',
    'Nuevo lunes, nueva energía',
    'Hoy empieza tu mejor semana',
    'Lunes con mentalidad de tiburón',
    'Dale con todo al lunes',
    'Lunes: día de sembrar lo que cosecharás el viernes',
    'Si ganaste el lunes, ganaste la semana',
    'Arranca el motor, que la semana apenas empieza',
    'El lunes es la primera victoria de la semana',
    'Lunes con ánimo es lunes invencible',
    'Hoy lunes se define el tono de toda la semana',
    'Lunes productivo = semana exitosa',
    'No hay lunes difícil para gente con actitud',
    'El lunes separa a los buenos de los excelentes',
    'Buen lunes, buen inicio, buena semana',
    'Lunes: oportunidad fresca de hacer las cosas bien',
    'El secreto del éxito empieza cada lunes',
    'Lunes warriors, reportándose',
    'Un lunes con propósito es un lunes ganado',
    'Dale play al lunes con toda la energía',
    'El lunes no es tu enemigo, es tu aliado',
    'Arrancando la semana con la mejor actitud',
    'Los lunes son para los que tienen metas grandes',
    'El café del lunes sabe a nueva oportunidad',
    'Lunes de arranque turbo. ¡Dale!',
    'Mientras otros odian el lunes, tú lo conquistas',
    'El lunes es la primera página de un gran capítulo',
    'Nuevo lunes, nuevo nivel desbloqueado',
    'Si el lunes fuera un partido, tú ya vas ganando',
    'Lunes: reset semanal completado. ¡A darle!',
    'El lunes premia a los que llegan con ganas',
    'Arrancamos la semana como se debe: con fuerza',
    'Los campeones aman los lunes porque son nuevos comienzos',
    'Lunes guerrero, semana victoriosa',
    'Tu energía de lunes le da vida a todo el equipo',
    'Hoy es lunes y eso significa: oportunidad fresca',
    'Lunes de oro para gente de oro',
  ];

  /** ===================== MARTES A JUEVES ===================== */
  private readonly MIDWEEK: string[] = [
    'A mitad de semana y sin parar',
    'Cada día cuenta, hoy también',
    'Seguimos sumando días de éxito',
    'Paso a paso se llega lejos',
    'Hoy es un buen día para dar el máximo',
    'La constancia es la clave del éxito',
    'Un día más cerca de la meta',
    'Sigue así, vas por buen camino',
    'Hoy también se puede ganar',
    'Ánimo, la semana avanza',
    'Entre semana es donde se forjan los campeones',
    'No bajes la guardia, la semana sigue',
    'A medio camino y con toda la fuerza',
    'Los días entre semana construyen tus logros',
    'Hoy es día de seguir sumando',
    'El éxito no descansa entre semana',
    'Mitad de semana, máxima entrega',
    'Cada día de la semana es una página nueva',
    'Hoy se trabaja con la misma pasión del lunes',
    'La consistencia entre semana es lo que marca la diferencia',
    'Día clave de la semana, a dar lo mejor',
    'Los grandes resultados se construyen entre lunes y viernes',
    'Hoy es perfecto para superar lo de ayer',
    'A mitad de semana se ve quién de verdad quiere',
    'Seguimos firmes, la meta está cerca',
    'Mitad de semana y la energía sigue al máximo',
    'Hoy es un día más para sumar puntos al marcador',
    'La semana es una carrera y tú vas adelante',
    'Entre semana es cuando se construyen las victorias',
    'Ni martes ni miércoles ni jueves te detienen',
    'La constancia entre semana define a los grandes',
    'Hoy se sigue construyendo el éxito paso a paso',
    'A medio camino y sin señales de cansancio',
    'Los días entre semana son los ladrillos del éxito',
    'Otro día para demostrar que la semana es tuya',
    'Mitad de semana con la misma fuerza del inicio',
    'El viernes se acerca, pero primero: productividad',
    'Hoy es día de mantener el ritmo ganador',
    'La semana avanza y tú avanzas con ella',
    'Cada día entre semana es una inversión en tu futuro',
    'Hoy es el día perfecto para superar metas',
    'A mitad de semana el compromiso brilla más',
  ];

  /** ===================== QUINCENA CERCANA ===================== */
  private readonly PAYDAY_CLOSE: string[] = [
    'Ya casi es quincena, a darle duro',
    'Se acerca la quincena y tú dando el ejemplo',
    'Falta poquito pa la quincena',
    'Quincena a la vuelta de la esquina',
    'Ya se siente la quincena cerca',
    'Unos días más y llega la recompensa',
    'La quincena se acerca, ¡qué bueno verte aquí!',
    'Falta nada pa cobrar, sigue así',
    'Con ese compromiso sí se gana la quincena',
    'Quincena incoming, ánimo total',
    'La quincena se huele, dale con todo',
    'Ya mero llega la recompensa al esfuerzo',
    'La quincena está cerca y tú cumpliendo como siempre',
    'Unos días más y se ve el fruto del trabajo',
    'La cuenta regresiva para la quincena ya empezó',
    'Quincena mode: activating...',
    'El esfuerzo de estos días vale doble, viene quincena',
    'Casi quincena, la recta final de la dedicación',
    'Pocos días para la recompensa, sigue así',
    'La quincena premia a los que no faltan',
    'Countdown quincenal activado. ¡Falta poco!',
    'El sobre se acerca y tú sigues firme',
    'Ya se puede oler la quincena desde aquí',
    'Tu esfuerzo pre-quincena no pasa desapercibido',
    'Días antes de quincena: motivación extra activada',
    'La quincena ya viene en camino, sigue dando el máximo',
    'Pre-quincena: la mejor época para dar lo mejor',
    'Quedan pocos días y la quincena te espera',
    'Tu dedicación de estos días la quincena la va a recompensar',
    'La quincena se acerca y tu compromiso sigue intacto',
    'Casi, casi... la quincena ya está a la vista',
    'El esfuerzo pre-quincena se paga doble en satisfacción',
  ];

  /** ===================== DÍA DE QUINCENA ===================== */
  private readonly PAYDAY: string[] = [
    '¡Día de quincena! Bien merecida',
    'Hoy es quincena y tú puntual, eso habla bien de ti',
    'Quincena day! A celebrar el esfuerzo',
    '¡Llegó la quincena! Gracias por tu dedicación',
    'Día de pago, día de orgullo',
    'La quincena llegó para quien se la merece',
    '¡Feliz quincena! Tu esfuerzo vale oro',
    'Quincena + puntualidad = combo ganador',
    'Hoy se cosecha lo sembrado. ¡Feliz quincena!',
    '¡Quincena! El premio al que madruga',
    '¡Es quincena, baby! Y tú aquí dando la cara',
    'Hoy pagan y tú puntual, así es como se hace',
    '¡Quincena! La recompensa al que no se rinde',
    'Día de cobro y de seguir brillando',
    '¡Feliz quincena! El esfuerzo tiene su premio',
    'Hoy suena la caja, bien merecido',
    '¡Quincena feliz! A disfrutar lo trabajado',
    'Puntual el día de pago, eso es compromiso real',
    '¡Llegó la quince! Gracias por cada día que diste el máximo',
    'Día de quincena y actitud de millonario',
    '¡Quincena time! El fruto de tu esfuerzo llega hoy',
    'Hoy el banco te sonríe y nosotros también',
    '¡Pay day! Y tú lo celebras llegando puntual',
    'La quincena es dulce cuando se trabaja con ganas',
    '¡Día de pago! Tu constancia finalmente cobra',
    'Quincena merecida para un trabajador de primera',
    '¡Hoy es quincena! Tu trabajo diario tiene recompensa',
    'El sobre llegó y tú también. ¡Felicidades!',
    '¡Quincena! Que la cuenta bancaria se alegre hoy',
    'Día de cobrar lo que te has ganado con creces',
    '¡Feliz quincena! El sueldo se gana, no se regala, y tú te lo ganaste',
    'Quincena y puntualidad: prueba de que eres profesional',
  ];

  /** ===================== SÁBADO ===================== */
  private readonly SATURDAY: string[] = [
    'Sábado y aquí dando la cara',
    'Trabajar en sábado es de valientes',
    'Sábado productivo, eso se respeta',
    'Un sábado de compromiso total',
    'Fin de semana y tú cumpliendo',
    'Sábado guerrero, así se hace',
    'El extra siempre se nota. Buen sábado',
    'Sábado con actitud de campeón',
    'Los sábados separan a los buenos de los grandes',
    'Sábado de hacer la diferencia',
    'Trabajar en sábado demuestra tu calibre',
    'Sábado + trabajo = dedicación nivel pro',
    'El sábado es para los que quieren más',
    'Mientras otros descansan, tú construyes tu futuro',
    'Sábado con ganas es sábado invencible',
    'El equipo agradece tu sacrificio sabatino',
    'Los grandes no descansan cuando hay meta que cumplir',
    'Sábado de campeones, bienvenido',
    'Tu compromiso del sábado habla más que mil palabras',
    'Fin de semana productivo, lunes sin preocupaciones',
    'Sábado laboral y con la mejor actitud',
    'Hoy es sábado pero tu compromiso no tiene calendario',
    'El sábado es el día extra que marca la diferencia',
    'Mientras el mundo duerme, tú ya estás ganando',
    'Sábado de profesionales. Bienvenido al club',
    'Tu presencia sabatina vale su peso en oro',
    'Sábado: día de dar ese extra que otros no dan',
    'El esfuerzo del sábado se paga con éxito',
    'Los sábados productivos construyen lunes tranquilos',
    'Hoy es sábado y tú eligiste la grandeza',
    'El sábado no es obligación cuando se tiene vocación',
  ];

  /** ===================== DOMINGO ===================== */
  private readonly SUNDAY: string[] = [
    'Domingo y aquí dando batalla',
    'Trabajar en domingo es de líderes',
    'Domingo con compromiso, eso vale mucho',
    'Un domingo más sirviendo con excelencia',
    'Domingo heroico, se agradece tu esfuerzo',
    'El que trabaja domingo merece aplausos',
    'Domingo: mientras el mundo duerme, tú produces',
    'Un domingo de entrega total',
    'Domingos así construyen carreras exitosas',
    'Tu dedicación dominical no pasa desapercibida',
    'Domingo y con la misma energía del lunes',
    'Los domingos productivos forjan a los líderes',
    'Hoy es domingo y tú estás aquí, eso dice mucho',
    'Domingo con propósito, domingo con valor',
    'El que da la milla extra el domingo, va dos pasos adelante',
    'Domingo de campeones, reportándose',
    'Tu sacrificio dominical es inspiración para el equipo',
    'Hoy es domingo y tú decidiste ser grande',
    'El domingo premia la dedicación con resultados',
    'Trabajar domingo es el nivel máximo de compromiso',
    'Domingo y con las pilas cargadas. ¡Admirable!',
    'El equipo valora tu presencia dominical',
  ];

  /** ===================== MADRUGADORES ===================== */
  private readonly EARLY_BIRD: string[] = [
    'Madrugaste, el éxito te espera',
    'Al que madruga Dios le ayuda',
    'Tempranero y comprometido, bien ahí',
    'Esa madrugada habla de tu carácter',
    'Primero en llegar, primero en triunfar',
    'Madrugar es de campeones',
    'La mañana premia a los valientes',
    'Arrancando temprano, así se gana',
    'Madrugador profesional, se nota el compromiso',
    'Ni el sol ha salido y tú ya estás aquí',
    'Los que madrugan tienen doble ventaja',
    'Temprano y con actitud, combo letal',
    'Mientras otros duermen, tú ya ganaste medio día',
    'Madrugón mode: ON. Éxito mode: ON',
    'La mañana es de los que se levantan primero',
    'Llegaste antes que el café, crack',
    'El amanecer te encontró listo para la batalla',
    'Los primeros en llegar son los últimos en rendirse',
    'Madrugón panameño de ley',
    'A esta hora solo están los que de verdad quieren',
    'El gallo todavía no cantó y tú ya marcaste',
    'Más temprano que el primer bus del corredor',
    'Tu almohada ni se enteró que te fuiste',
    'Madrugada productiva en progreso',
    'El sol te debe una disculpa por llegar tarde',
    'Esa madrugada merece un premio',
    'A esta hora el café todavía se está haciendo',
    'Madrugador élite, categoría diamante',
    'Llegaste tan temprano que el edificio se sorprendió',
    'Tu despertador ni sonó y ya estás aquí',
    'Los pájaros todavía duermen y tú ya marcaste',
    'El amanecer es tu hora de poder',
  ];

  /** ===================== TARDANZA ===================== */
  private readonly LATE_ARRIVAL: string[] = [
    'Mejor tarde que nunca, ¡ánimo!',
    'Ya estás aquí, eso es lo que importa',
    'Llegaste, ahora a dar lo mejor',
    'El día aún tiene mucho por dar',
    'Lo importante es que viniste, a recuperar',
    'Aún queda día para brillar',
    'Ya estamos, ahora con todo',
    'Cada minuto cuenta, a aprovecharlo',
    'La puntualidad de mañana empieza con el compromiso de hoy',
    'Llegamos un poco tarde, pero con ganas de sobra',
    'El reloj dice tarde, pero tu actitud dice a tiempo',
    'Hoy empezamos un poquito después, mañana más temprano',
    'Lo bueno es que estás aquí, ahora dale con fuerza',
    'Tarde pero seguro, mañana puntual',
    'No es el mejor inicio, pero el final depende de ti',
    'El día no se perdió, aún hay mucho por ganar',
    'Llegaste y eso ya es un paso adelante',
    'Mañana el despertador gana, hoy ganas tú con actitud',
    'Un tropiezo no define tu día, tu esfuerzo sí',
    'El tráfico no te venció, aquí estás',
    'Lo importante no es cuándo llegaste sino qué haces ahora',
    'El día aún tiene horas para demostrar tu valor',
    'Tarde hoy, puntual mañana. El compromiso se ve',
    'Llegaste y eso ya cuenta. Ahora a dar el 100%',
    'El reloj marca tardanza, pero tu corazón marca ganas',
    'No fue el inicio perfecto, pero aún puedes cerrar como campeón',
    'El tráfico panameño no es excusa, pero se entiende',
    'Hoy el tranque ganó, pero mañana ganas tú',
    'Llegaste un poco después, pero con toda la actitud',
    'Un inicio tardío no determina un día malo',
    'El día todavía tiene potencial, aprovéchalo',
    'La Tumba Muerto estaba imposible, ¿verdad?',
    'Hoy el corredor te ganó, mañana lo vences tú',
    'Cada minuto que queda es una oportunidad de brillar',
    'El día no empieza cuando llegas, empieza cuando das el máximo',
    'Un poco tarde pero con toda la energía del mundo',
    'El tráfico de la capital cobra otra víctima, pero sobreviviste',
    'Llegaste. Eso ya es ganar la primera batalla del día',
    'Tarde pero con la actitud de un campeón',
    'Mañana madrugamos más, hoy trabajamos más duro',
    'El reloj no mide las ganas, y tú traes de sobra',
    'Mejor tarde que ausente. ¡A darle con todo!',
    'El tranque te adoptó como hijo, pero te escapaste',
    'Google Maps dice 20 minutos, Panamá dice otra cosa',
    'Llegaste, eso ya te pone por encima de tu cama',
    'La Tumba Muerto cobró otra víctima, pero sobreviviste',
    'Tu almohada peleó duro, pero tú ganaste al final',
    'El despertador hizo lo suyo, el snooze hizo lo contrario',
    'Viniste y eso demuestra que el tranque no manda aquí',
    'La cama te retuvo como rehén pero negociaste tu libertad',
    'Hoy la ruta fue un nivel de Mario Bros en modo difícil',
    'El corredor sur te hizo un examen de paciencia y pasaste',
    'Tu relación con el snooze es complicada, pero estás aquí',
    'Si el tráfico fuera una asignatura, hoy te reprobó. Pero viniste',
    'El Metro estaba lleno pero tu voluntad estaba más llena',
    'Hoy Panamá se confabuló contra ti pero no pudo',
  ];

  /** ===================== PANAMEÑAS ===================== */
  private readonly PANAMANIAN: string[] = [
    'Échale ganas, panameño',
    'Con sabor a Panamá y ganas de triunfar',
    'El panameño no se rinde, ¡dale!',
    'Pura cepa canalera',
    'Con la fuerza del Canal',
    'Orgullo panameño en cada marcada',
    'Istmo de campeones',
    'Panamá en el corazón, trabajo en las manos',
    'Aquí se trabaja con garra panameña',
    'Del Puente de las Américas al éxito',
    'Tierra de Balboa y de gente trabajadora',
    'Con el espíritu del 9 de enero',
    'Sangre panameña, esfuerzo de campeón',
    'De Panamá para el mundo, dando el ejemplo',
    'Cinta Costera vibes: siempre hacia adelante',
    'Más fuerte que el verano panameño',
    'Con la misma fuerza que cruza el Canal',
    'Somos el puente del mundo, corazón del universo',
    'Panameño y orgulloso de trabajar duro',
    'Aquí nadie se queda atrás, somos istmeños',
    'Con esa garra panameña no hay quien pueda',
    'Dale panameño, que la chamba no se hace sola',
    'Panamá: país chiquito con gente grande',
    'Con la actitud del que cruza el Canal a diario',
    'Más panameño que el sancocho y más trabajador que nadie',
    'Con sabor a empanada y ganas de echar pa lante',
    'Del Chorrillo al éxito, sin escalas',
    'Panameño trabajador: la mejor marca de origen',
    'Con esa energía típica panameña',
    'Como buen panameño: con calle y con clase',
    'Istmo power, activado',
    'Panamá no es solo un canal, es gente que trabaja duro',
    'Con la misma actitud que construyó el Canal',
    'Panameño y puntual, la mejor combinación',
    'Aquí se trabaja como se vive: con pasión panameña',
    'Tan fuerte como el cafecito de la mañana panameña',
    'Con la determinación de cruzar el Darién',
    'Orgullosamente panameño, orgullosamente puntual',
    'Con el flow del Casco Viejo: clásico pero moderno',
    'Como dice el panameño: ¡dale que dale!',
    'Con más fuerza que un aguacero en la capital',
    'Del interior al éxito, con orgullo',
    'Panameño de ley, trabajador de corazón',
    'Con la alegría de un día de carnavales',
    'Más puntual que el bus de Metrobús... bueno, casi',
    'Con la misma energía que un domingo de playa',
    'Típico panameño: trabajador y echao pa lante',
    'De San Miguelito a la cima, sin parar',
    'Con el ritmo panameño en las venas',
    'Aquí se trabaja con sabor a Panamá',
    'Con la brisa de la Calzada de Amador en el ánimo',
    'Más firme que la Torre de Panamá la Vieja',
    'Con la calidez del panameño y la fuerza del istmeño',
    'Del corredor sur al corredor del éxito',
    'Panameño de cepa: trabajador y cumplidor',
    'Con el swing panameño en cada paso',
    'Como la marea del Pacífico: siempre volviendo con fuerza',
    'Más activo que el Mercado de Mariscos un domingo',
    'Con el espíritu de los que construyeron la nación',
    'Del Causeway al escritorio sin perder el ritmo',
    'Tan constante como las lluvias de octubre en Panamá',
    'Con la energía de la Calle Uruguay un sábado',
    'Istmeño hasta la médula, trabajador hasta el final',
    'Con la pasión de un partido de la Sele en el Rommel',
    'Más panameño que un diablo rojo en hora pico',
    'Con el orgullo de 3 de noviembre en cada jornada',
    'Del Clayton al centro con toda la actitud',
    'Panameño que se respeta llega y da la cara',
    'Con más flow que el reggaetón panameño',
    'Firme como el Cerro Ancón, imparable como el Canal',
    'Con la misma garra que sacó a los gringos de la Zona',
    'Más trabajador que vendedor de raspao en verano',
    'Con el sabor panameño en cada logro',
    'Del metro a la oficina sin perder la chispa',
    'Tan panameño como una pollera un 3 de noviembre',
    'Con la actitud de quien lleva el istmo en la sangre',
    'Panameño 24/7: trabajador, alegre y echao pa lante',
    'Con la determinación del que cruza el puente en hora pico',
    'Más resiliente que panameño en tranque',
    'Con el corazón en Panamá y las ganas en el trabajo',
    'Istmo proud: llegando y cumpliendo cada día',
    'Del Pacific Mall al éxito profesional',
  ];

  /** ===================== FRASES CÉLEBRES PANAMEÑAS ===================== */
  private readonly FAMOUS_PANAMA: string[] = [
    '"La patria es ara y no pedestal" — Justo Arosemena',
    '"En la lucha por la libertad todos los días son buenos" — Victoriano Lorenzo',
    '"Ni millonarios ni muertos de hambre" — Omar Torrijos',
    '"Panamá para los panameños" — Grito generacional',
    '"El trabajo dignifica al hombre" — Dicho panameño',
    '"La educación es el arma más poderosa" — Adaptado por maestros panameños',
    '"Cada día es una oportunidad de ser mejor" — Sabiduría istmeña',
    '"El que persevera alcanza" — Dicho popular panameño',
    '"Primero la patria" — Lema patriota panameño',
    '"Con unidad todo se logra" — Espíritu del 3 de noviembre',
    '"No hay distancia que no se pueda recorrer" — Dicho canalero',
    '"El esfuerzo de hoy es el triunfo de mañana" — Proverbio panameño',
    '"Somos pequeños pero echados pa lante" — Dicho popular',
    '"Panameño que se respeta, madruga y trabaja" — Refrán popular',
    '"La disciplina tarde o temprano vence a la inteligencia" — Sabiduría istmeña',
    '"El que no arriesga, ni gana ni pierde" — Dicho panameño',
    '"Más vale maña que fuerza" — Refrán panameño',
    '"Al mal tiempo, buena cara" — Sabiduría popular panameña',
    '"Quien siembra, cosecha" — Proverbio istmeño',
    '"La unión hace la fuerza" — Lema centroamericano',
    '"El Canal no se hizo en un día" — Sabiduría canalera',
    '"Pueblo que no conoce su historia está condenado a repetirla" — Lección panameña',
    '"Lo que Dios quiera y Panamá disponga" — Dicho panameño',
    '"El istmo une lo que el mar separa" — Proverbio geográfico',
    '"El que madruga coge agua clara" — Refrán del interior',
    '"En Panamá todo se puede cuando se quiere" — Espíritu istmeño',
    '"El trabajo honrado siempre tiene recompensa" — Dicho campesino panameño',
    '"Pa lante es pa lla" — Filosofía panameña de vida',
    '"La lluvia no detiene al panameño de ley" — Dicho capitalino',
    '"Con paciencia y saliva, el elefante se comió a la hormiga" — Refrán panameño',
    '"El que tiene tienda que la atienda" — Refrán popular panameño',
    '"A Dios rogando y con el mazo dando" — Sabiduría campesina panameña',
  ];

  /** ===================== GENERALES ===================== */
  private readonly GENERAL: string[] = [
    'Hoy va a ser un gran día',
    'Tu esfuerzo no pasa desapercibido',
    'Gracias por tu compromiso',
    'Cada día cuentas más',
    'Eres parte importante del equipo',
    'Tu puntualidad marca la diferencia',
    'Sigue con esa actitud ganadora',
    'El éxito se construye día a día',
    'Hoy es un buen día para ser excelente',
    'Tu presencia hace la diferencia',
    'El equipo cuenta contigo',
    'Otro día, otra oportunidad de brillar',
    'La consistencia te hace grande',
    'Vas por excelente camino',
    'Ese compromiso se nota',
    'Un día más de excelencia',
    'Tu dedicación inspira',
    'Bienvenido a otro día de logros',
    'La actitud lo es todo, y la tuya es ganadora',
    'Hoy es el día perfecto para dar tu mejor versión',
    'Tu trabajo tiene valor, gracias por estar',
    'La excelencia es un hábito, y tú lo demuestras',
    'Sigue sumando días de grandeza',
    'Cada marca es un paso hacia el éxito',
    'Tu compromiso es tu mejor carta de presentación',
    'Hoy también se puede lograr algo increíble',
    'La disciplina abre puertas',
    'El mejor momento es ahora',
    'Eres más fuerte de lo que crees',
    'Hoy es otro día para dejar huella',
    'Tu constancia dice mucho de ti',
    'Un día productivo empieza con llegar',
    'Nada detiene a quien tiene actitud',
    'Tu mejor versión está en construcción',
    'Hoy trae oportunidades nuevas',
    'Que nada apague tu energía hoy',
    'El éxito ama a los puntuales',
    'Hacer lo correcto siempre vale la pena',
    'Tu trabajo es semilla de grandes cosas',
    'Empieza el día con gratitud y energía',
    'Eres pieza clave en este engranaje',
    'El esfuerzo silencioso es el más poderoso',
    'Día a día construyes tu legado',
    'Confía en el proceso, vas bien',
    'Quien llega puntual, ya ganó la mitad',
    'Tu energía contagia al equipo',
    'Nada como empezar el día cumpliendo',
    'Con esa actitud llegas lejos',
    'Hoy es una página en blanco, escríbela bien',
    'El trabajo duro siempre paga',
    'Eres el motor de este equipo',
    'Gracias por ser parte de esto',
    'Que este día supere al anterior',
    'Tu dedicación tiene nombre y apellido',
    'Hoy también es día de victoria',
    'Sigue adelante, el camino es tuyo',
    'El mundo necesita gente como tú',
    'Arrancamos con todo hoy',
    'Nada es imposible para quien se presenta',
    'Tu compromiso es inspiración',
    'Llegaste y eso ya es ganar',
    'Hoy eres imparable',
    'La puntualidad es tu superpoder',
    'Otro día demostrando de qué estás hecho',
    'Tu responsabilidad habla más que mil palabras',
    'A darle con ganas que el día es tuyo',
    'Nadie puede detenerte hoy',
    'Tú marcas el ritmo del equipo',
    'Profesionalismo se deletrea con tu nombre',
    'La excelencia no es un acto, es un hábito',
    'Tu ejemplo motiva a los demás',
    'Hoy traes buena vibra, se siente',
    'Constancia + actitud = éxito asegurado',
    'Que nada te quite las ganas hoy',
    'Firme como el Cerro Ancón',
    'Dale que la vida premia al constante',
    'Siempre se puede un poco más',
    'Con ese flow no hay quien te pare',
    'Llegaste primero que el café, crack',
    'Hoy vas a romperla, ya lo sé',
    'El que se levanta temprano tiene doble ventaja',
    'Cada día es una nueva victoria',
    'Tú haces que este lugar funcione mejor',
    'Excelente inicio de jornada',
    'Arriba ese ánimo, hoy será épico',
    'Tu presencia aporta valor, siempre',
    'Hoy se respira productividad',
    'Cada mañana trae una promesa, hoy cumple la tuya',
    'Eres de los que hacen que las cosas pasen',
    'Aquí se nota quién quiere y quién no. Tú quieres',
    'El talento es llegar, la grandeza es quedarse',
    'Hoy el equipo está más fuerte contigo',
    'Tu disciplina construye el éxito de todos',
    'Brillar es tu estado natural',
    'Los grandes empiezan temprano, como tú',
    'Otro día, otro paso hacia la cima',
    'Tu compromiso no tiene precio',
    'Hoy el protagonista eres tú',
    'A darle con la misma fuerza de siempre',
    'Nadie te puede quitar las ganas',
    'El equipo necesita gente como tú',
    'Hoy es día de hacer historia',
    'Tu constancia es tu mejor inversión',
    'Otro día más cerca del objetivo',
    'Actitud positiva: cargada al 100%',
    'El éxito no es casualidad, es constancia',
    'Hoy se trabaja con alma y corazón',
    'Tu esfuerzo de hoy es tu premio de mañana',
    'La grandeza está en los pequeños actos diarios',
    'Eres más capaz de lo que imaginas',
    'Hoy es tu día para sorprender',
    'Nada mejor que empezar el día con propósito',
    'Tu trabajo importa más de lo que crees',
    'Otro día para demostrar tu valor',
    'Con esa energía, hoy es tuyo',
    'El compromiso se demuestra cada día, y hoy lo demostraste',
    'Tu actitud positiva es contagiosa',
    'Hoy el éxito tiene tu nombre',
    'La clave del éxito es la persistencia, y tú la tienes',
    'Cada jornada es un paso más hacia tus metas',
    'Tu profesionalismo es admirable',
    'Hoy es un lienzo en blanco y tú eres el artista',
    'El compromiso diario es lo que separa a los buenos de los grandes',
    'Tu trabajo deja marca en todo lo que tocas',
    'Gracias por aportar tu energía cada día',
    'El equipo brilla más cuando tú estás',
    'Hoy es otro día para crecer y mejorar',
    'Tu dedicación es el ejemplo que muchos necesitan',
    'Cada día que vienes es un día que sumas',
    'El secreto del éxito eres tú y tu constancia',
    'Hoy el día empieza con tu mejor versión',
    'La disciplina es el puente entre metas y logros',
    'Tu presencia eleva el nivel del equipo',
    'Hoy vienes con la energía perfecta para ganar',
    'Que tu día sea tan productivo como tu actitud',
    'Tu compromiso es la base del éxito colectivo',
    'Cada marca de entrada es una promesa de excelencia',
    'El mundo laboral necesita más gente como tú',
    'Hoy arrancas con la ventaja de tu actitud',
    'Que el día de hoy sea tu obra maestra',
    'Tu puntualidad refleja tu carácter',
    'Eres de los que construyen el futuro, un día a la vez',
    'Hoy es perfecto para superar tus propios récords',
    'Con esa energía no hay meta inalcanzable',
    'Tu esfuerzo diario construye imperios',
    'Bienvenido a otro día de hacer la diferencia',
    'La grandeza no se hereda, se trabaja. Y tú lo haces',
    'Hoy tu dedicación marca el camino para otros',
    'Cada día eres un poco mejor, y eso es grandioso',
    'Tu constancia es tu superpoder secreto',
    'Arrancamos otro día con toda la actitud ganadora',
    'El éxito te busca porque tú no dejas de buscarlo',
    'Hoy se respira grandeza en el ambiente',
    'Tu trabajo diario es la mejor inversión que existe',
  ];

  /** ===================== MASCOTAS / BLACK DOG ===================== */
  private readonly PET_VIBES: string[] = [
    'Hoy viniste con la energía de un cachorro feliz',
    'Puntual como un perrito esperando su comida',
    'Con la lealtad de un buen perro, siempre presente',
    'Llegaste moviendo la cola de la emoción',
    'Firme como un bulldog, constante como un golden',
    'Con el olfato del éxito activado',
    'Hoy traes energía de perrito en el parque',
    'Tan confiable como un perro guardián',
    'Con la alegría de un cachorro en día de paseo',
    'Fiel al trabajo como un perro a su dueño',
    'Ladrando al éxito desde temprano',
    'Con la misma emoción que un perro viendo a su humano',
    'Hoy llegaste con todo: collar, correa y actitud',
    'Como buen Black Dog: fuerte, leal y trabajador',
    'El mejor amigo del equipo llegó',
    'Con la energía de un golden retriever al que le dijeron paseo',
    'Leal como un labrador, puntual como un reloj',
    'Si fueras perrito, serías el que siempre trae la pelota',
    'Black Dog energy: proteger la manada y cumplir la misión',
    'Hoy llegaste con más cola que un husky emocionado',
    'Tu compromiso tiene la fidelidad de un perro rescatado',
    'Con la determinación de un pastor alemán en servicio',
    'Llegaste como cachorro a su primera aventura: con emoción',
    'El equipo te recibe como perrito a su humano favorito',
    'Con el instinto ganador de un perro de competencia',
    'Tan entusiasta como mascota en día de baño... bueno, casi',
    'Black Dog approved: llegaste, cumpliste, la rompiste',
    'Con el espíritu juguetón de un cachorro y la disciplina de un K9',
    'Si la puntualidad fuera un truco canino, ya serías campeón',
    'Hoy traes la felicidad de un perrito con juguete nuevo',
    'Como perro con dos colas: llegaste feliz y listo para trabajar',
    'Tu energía hoy es nivel cachorro después de la siesta',
    'Con la misma dedicación que un perro persiguiendo su pelota',
    'Black Dog lo aprueba: otro día de excelencia perruna',
    'Llegaste con más ánimo que perrito oyendo la bolsa de croquetas',
    'Fiel al horario como mascota fiel a su rutina',
    'Tu puntualidad merece un premio... o un snack canino',
    'Con la nobleza de un golden y la fuerza de un rottweiler',
    'Hoy el equipo te recibe con más amor que perrito adoptado',
    'Black Dog vibes: lealtad, fuerza y mucha actitud',
    'Tan confiable como mascota esperando en la puerta',
    'Llegaste con la energía de cachorro que descubrió el jardín',
  ];

  /** ===================== HUMOR ===================== */
  private readonly HUMOR: string[] = [
    'El café te espera, pero tu compromiso llegó primero',
    'Hoy el café tiene que alcanzarte a ti',
    'Antes del café ya estás produciendo, crack',
    'Que el café sea tan fuerte como tu compromiso',
    'Modo oficina: activado. Modo café: pendiente',
    'Ni el tráfico te detuvo, eres imparable',
    'Tu despertador debe estar orgulloso',
    'Hoy le ganaste al snooze, campeón',
    'Sobreviviste al tráfico: primer logro del día',
    'Tu almohada te extraña pero el equipo te necesita',
    'Hoy el tráfico de Panamá no pudo contigo',
    'El aire acondicionado te esperaba',
    'Ganaste la batalla contra la cama, héroe',
    'El microondas del almuerzo se calentó de la emoción',
    'Hoy hasta la impresora está contenta de verte',
    'Tu cama hizo todo lo posible por retenerte, pero fallaste... digo, triunfaste',
    'Si el tráfico fuera deporte olímpico, tendrías medalla de oro',
    'El WiFi te extrañaba, bienvenido de vuelta',
    'Tu silla de trabajo respiró de alivio al verte',
    'El ascensor te estaba esperando, eso es VIP',
    'Llegaste con más energía que el grupo de WhatsApp de la oficina',
    'El correo electrónico acaba de temblar al verte llegar',
    'Hoy tu cara dice lunes pero tu actitud dice viernes',
    'El snooze perdió otra batalla. Invicto: tú',
    'Tu computadora ya estaba calentando para ti',
    'El tráfico te dio batalla pero aquí estás, guerrero',
    'La cafetera te guiñó el ojo al verte entrar',
    'Hoy hasta Excel está contento de verte',
    'Tu escritorio te recibió con los brazos abiertos',
    'Si madrugar fuera fácil, todos lo harían. Tú lo haces',
    'Hoy el espejo dijo: ese es un trabajador de élite',
    'El estacionamiento te reservó el mejor puesto',
    'Tu despertador: misión cumplida. Snooze: derrotado',
    'Sobreviviste al lunes, al tráfico y al despertador. ¡Leyenda!',
    'Llegaste antes que la mitad de los correos del día',
    'El chat de la oficina ya tiene su primer mensaje: tú marcaste',
    'La máquina de café ya te vio y empezó a prepararse',
    'Tu laptop aplaudió internamente cuando la encendiste',
    'El elevador subió más rápido hoy, sabía que venías',
    'Hoy el tráfico intentó, pero tu voluntad fue más fuerte',
    'Si puntualidad pagara doble, serías millonario',
    'El AC estaba esperando a alguien que lo mereciera: tú',
    'Ni la lluvia, ni el tranque, ni el snooze te detuvieron',
    'Llegaste con más determinación que email urgente del jefe',
    'El parking te recibió como a un viejo amigo',
    'Tu café matutino brindó por tu puntualidad',
    'Si la batalla fuera el tráfico, tú eres el general',
    'Tu cama lloró cuando te fuiste, pero el trabajo celebró cuando llegaste',
    'Hoy hasta el servidor está de buen humor porque llegaste',
    'El botón de snooze ya se rindió contigo',
    'Si convertimos tu puntualidad en energía, iluminamos la oficina',
    'Tu agenda del día tembló cuando te vio llegar tan decidido',
    'El café se hace mejor cuando tú llegas temprano',
    'La silla del escritorio se ajustó sola al sentir tu presencia',
    'Hoy el día arrancó oficialmente porque llegaste tú',
    'Tu puntualidad debería cotizar en la bolsa',
    'El edificio entero se activó cuando pasaste la puerta',
    'Sobreviviste a la Tumba Muerto en hora pico: eres inmortal',
    'Hoy el reloj hizo una reverencia cuando marcaste',
    'Tu compromiso llegó antes que tu café, y eso es mucho decir',
    'La oficina brilla más cuando llegas. O es el reflejo del monitor',
    'Llegaste con más energía que notificación de WhatsApp a las 7am',
    'Tu cama presentó una queja formal por abandono',
    'Llegaste antes que el chisme del día, eso es velocidad',
    'Tu despertador publicó un comunicado: misión cumplida',
    'La almohada intentó sobornarte pero tu ética es más fuerte',
    'El café de la oficina se hizo solo cuando te detectó llegando',
    'Llegaste tan puntual que el reloj te pidió autógrafo',
    'Tu cobija lloró, tu jefe sonrió. Decisiones difíciles',
    'Si pagan por puntualidad, hoy te toca bono',
    'Hoy llegaste con más ganas que perrito al escuchar "paseo"',
    'Ni Netflix te retuvo anoche, eso es disciplina',
    'Si la puntualidad fuera un deporte, estarías en el Hall de la Fama',
    'Llegaste antes que la excusa del tráfico. Nivel: leyenda',
    'Tu mamá estaría orgullosa de esta puntualidad',
    'Hoy viniste con la velocidad de cuando el jefe dice "reunión a las 8"',
    'Llegaste tan rápido que el Waze se confundió',
    'Si existiera el premio Nobel de puntualidad, ya tendrías tres',
    'Ni un meteorito te detiene. Bueno, quizás ese sí',
    'Tu compromiso es más fuerte que la señal del WiFi',
    'Hoy el día oficial empezó cuando tú llegaste, no cuando salió el sol',
    'Llegaste con más determinación que lunes sin café',
    'Tu puntualidad tiene más seguidores que influencer panameño',
    'El guardia de seguridad aplaudió internamente',
    'Hoy tu alarma sonó y tú dijiste: challenge accepted',
    'Si tu puntualidad fuera criptomoneda, estaría en all-time high',
    'Llegaste más rápido que chisme en grupo de WhatsApp',
    'Tu presencia iluminó la oficina... o fue que encendieron las luces',
    'Hoy el tráfico te vio venir y se quitó del camino',
    'Tu GPS te puso como ejemplo de ruta eficiente',
    'La puerta de la oficina se abrió sola de la emoción',
    'Tan puntual que el microondas ya calentó tu almuerzo por adelantado',
    'Si tu puntualidad fuera meme, ya sería viral',
    'El aire acondicionado sopló más fuerte al sentir tu presencia',
    'Hoy hasta Siri te dijo: wow, llegaste temprano',
    'Tu récord de asistencia ya necesita su propia base de datos',
    'Ni el meme del "ya voy saliendo" te define. Tú SÍ sales',
    'Llegaste antes de que alguien pudiera decir "¿dónde está?"',
    'Tu café matutino brindó en tu honor',
    'Hoy viniste con la energía de un viernes a las 4:59pm',
    'Si la puntualidad midiera centímetros, medirías 3 metros',
  ];

  /** ===================== COMIDA PANAMEÑA ===================== */
  private readonly COMIDA_PTY: string[] = [
    'Llegaste con más sabor que un sancocho de gallina',
    'Más puntual que arroz con pollo un domingo',
    'Con la sazón panameña en cada paso',
    'Hoy vienes con energía de hojaldre recién hecho',
    'Tan bueno como una carimañola de queso',
    'Más fresco que un raspao en el calor',
    'Con la puntualidad de una empanada caliente',
    'Llegaste como ceviche: fresco y a punto',
    'Hoy traes la energía de un plato de arroz con guandú',
    'Tan indispensable como el culantro en la cocina panameña',
    'Con más sabor que un tamal de olla',
    'Llegaste como patacón: firme y crujiente',
    'Hoy vienes recargado como arroz con coco',
    'Con la dulzura de un bienmesabe y la fuerza de un sancocho',
    'Tan puntual como el almuerzo del domingo',
    'Tu llegada tiene más sabor que tortilla con queso blanco',
    'Más consistente que el arroz blanco en el almuerzo',
    'Con la energía de un desayuno de hojaldres con salchichas',
    'Tan reconfortante como un caldo de costilla',
    'Llegaste con el sabor del rondón caribeño',
    'Más completo que un plato de corvina frita con patacones',
    'Con la frescura de un jugo de naranja recién exprimido',
    'Tu presencia tiene el mismo efecto que un café bien cargado',
    'Más bienvenido que tortilla de maíz en el desayuno',
    'Con la contundencia de un guacho de mariscos',
    'Tan esperado como el sancocho del sábado',
    'Llegaste con la calidez de una sopa de mondongo',
    'Más auténtico que un chicheme del interior',
    'Con la fuerza de un bolón de plátano maduro',
    'Tu compromiso es tan fuerte como café de Boquete',
    'Más rico que un plato de ropa vieja panameña',
    'Con la consistencia de un buen plato de frijoles con chicharrón',
    'Llegaste fresco como ceviche de corvina',
    'Tan necesario como la sal en el sancocho',
    'Con más punch que un jugo de caña recién hecho',
    'Tu energía es nivel hojaldre de la mañana',
    'Más puntual que el señor del raspao en verano',
    'Con la dulzura de un cocada del Chorrillo',
    'Llegaste con la sazón de un almuerzo de fonda',
    'Tan irresistible como un plato de tamales navideños',
    'Con la frescura de un agua de pipa en Coronado',
    'Más reconfortante que arroz con leche un día lluvioso',
    'Tu llegada tiene sabor a chicha de maíz nuevo',
    'Con la potencia de un guacho de rabito de puerco',
    'Tan tradicional como el arroz con guandú en Navidad',
    'Llegaste con la energía de quien desayunó doble hojaldre',
    'Más sabroso que yuca frita con suero',
    'Con el sabor auténtico de una tortilla asada en fogón',
    'Tu presencia alegra como postre de tres leches',
    'Más panameño que un almuerzo de domingo con la familia',
    'Llegaste como tasajo: con carácter y sabor',
    'Con la dulzura de un pesao de nance',
  ];

  /** ===================== GENERALES PERSONALIZADAS ===================== */
  private readonly GENERAL_PERSONALIZED: PhraseGen[] = [
    (n, g) => `¡${n}! Hoy va a ser un día épico`,
    (n, g) => `${n}, el equipo brilla más cuando estás aquí`,
    (n, g) => `¡Bienvenid${g === 'F' ? 'a' : 'o'}, ${n}! El día está esperando`,
    (n, g) => `${n}, tu puntualidad es un ejemplo para tod${g === 'F' ? 'as' : 'os'}`,
    (n, g) => `¡Arranca con todo el día, ${n}!`,
    (n, g) => `${n}, qué bueno verte por aquí`,
    (n, g) => `¡${n}, hoy eres imparable!`,
    (n, g) => `${n}, tu presencia hace la diferencia`,
    (n, g) => `Gracias por tu compromiso, ${n}`,
    (n, g) => `¡${n}, campeón${g === 'F' ? 'a' : ''}! El día es tuyo`,
    (n, g) => `${n}, otro día de demostrar de qué estás hech${g === 'F' ? 'a' : 'o'}`,
    (n, g) => `¡${n}! Con esa actitud no hay quien te pare`,
    (n, g) => `${n}, eres de l${g === 'F' ? 'a' : 'o'}s que hacen grande este equipo`,
    (n, g) => `¡Buenos días, ${n}! Hoy todo va a salir bien`,
    (n, g) => `${n}, tu energía hoy contagia a todo el equipo`,
    (n, g) => `¡${n}, hoy el protagonista eres tú!`,
    (n, g) => `La jornada de hoy tiene tu nombre, ${n}`,
    (n, g) => `¡${n}! Llegaste a dominar el día`,
    (n, g) => `${n}, eres pieza clave de este equipo`,
    (n, g) => `¡Llegó ${g === 'F' ? 'la campeona' : 'el campeón'}! Bienvenid${g === 'F' ? 'a' : 'o'}, ${n}`,
    (n, g) => `${n}, hoy es el día perfecto para brillar`,
    (n, g) => `¡${n}, el equipo te necesitaba!`,
    (n, g) => `Cada día que llegas, ${n}, el equipo es más fuerte`,
    (n, g) => `${n}, tu compromiso no tiene precio`,
    (n, g) => `¡${n}! Con vos el equipo es invencible`,
    (n, g) => `${n}, eres de l${g === 'F' ? 'a' : 'o'}s mejores que hay aquí`,
    (n, g) => `Hoy ${n} llegó y el día mejoró al instante`,
    (n, g) => `¡Qué bueno que estás aquí, ${n}!`,
    (n, g) => `${n}, tu constancia habla más que mil palabras`,
    (n, g) => `¡${n}, a darle que hoy se puede todo!`,
  ];

  /**
   * Main method - context-aware phrase selection.
   * Priority: birthday > type-specific > late > payday > day > time > themed > general
   */
  public getPhrase(isLate = false, isBirthday = false, type = 'entry', exitDiffMinutes?: number, isLunchOvertime = false, name?: string, gender?: 'M' | 'F'): string {
    if (isBirthday) return this.pick(this.BIRTHDAY);

    // Type-specific phrases for non-entry types
    if (type === 'lunch_start') return this.pick(this.LUNCH_START);
    if (type === 'lunch_end' && isLunchOvertime) {
      return Math.random() < 0.7 ? this.pick(this.LUNCH_OVERTIME) : this.pick(this.LUNCH_END);
    }
    if (type === 'lunch_end') return this.pick(this.LUNCH_END);
    if (type === 'exit') {
      // Check if exit was punctual (within 2 minutes of scheduled exit)
      if (exitDiffMinutes !== undefined && exitDiffMinutes >= 0 && exitDiffMinutes <= 2) {
        // 60% chance of funny punctual phrase, 40% normal exit
        if (Math.random() < 0.6) return this.pick(this.EXIT_PUNCTUAL);
      }
      // Check if leaving early (more than 15 min before scheduled)
      if (exitDiffMinutes !== undefined && exitDiffMinutes < -15) {
        return this.pick(this.EXIT_EARLY);
      }
      return this.pick(this.EXIT);
    }

    // Entry-type logic (original flow)
    if (isLate) return this.pick(this.LATE_ARRIVAL);

    const now = new Date();
    const ctx: PhraseContext = {
      dayOfWeek: now.getDay(),
      dayOfMonth: now.getDate(),
      hour: now.getHours(),
      isLate,
      type,
    };

    const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
    if (ctx.dayOfMonth === 15 || ctx.dayOfMonth === lastDay) return this.pick(this.PAYDAY);

    const daysTo15 = 15 - ctx.dayOfMonth;
    const daysToEnd = lastDay - ctx.dayOfMonth;
    if ((daysTo15 > 0 && daysTo15 <= 3) || (daysToEnd > 0 && daysToEnd <= 3)) {
      if (Math.random() < 0.4) return this.pick(this.PAYDAY_CLOSE);
    }

    if (ctx.hour < 7 && Math.random() < 0.5) return this.pick(this.EARLY_BIRD);

    const dayPool = this.getDayPool(ctx.dayOfWeek);
    if (dayPool && Math.random() < 0.4) return this.pick(dayPool);

    const roll = Math.random();
    if (roll < 0.12) return this.pick(this.PET_VIBES);
    if (roll < 0.32) return this.pick(this.HUMOR);
    if (roll < 0.42) return this.pick(this.COMIDA_PTY);
    if (roll < 0.52) return Math.random() < 0.5 ? this.pick(this.PANAMANIAN) : this.pick(this.FAMOUS_PANAMA);

    if (name && Math.random() < 0.45) {
      const fn = this.GENERAL_PERSONALIZED[Math.floor(Math.random() * this.GENERAL_PERSONALIZED.length)];
      return fn(name, gender);
    }
    return this.pick(this.GENERAL);
  }

  public getBirthdayPhrase(): string {
    return this.pick(this.BIRTHDAY);
  }

  private getDayPool(day: number): string[] | null {
    switch (day) {
      case 0: return this.SUNDAY;
      case 1: return this.MONDAY;
      case 5: return this.FRIDAY;
      case 6: return this.SATURDAY;
      default: return this.MIDWEEK;
    }
  }

  private pick(arr: string[]): string {
    return arr[Math.floor(Math.random() * arr.length)];
  }
}
